services:
  - type: web
    name: barber-shop
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    buildCommand: ""
    startCommand: apache2-foreground
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: prod
    preDeployCommand: php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
